apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecai-deploy
  labels:
    app: ecai-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecai-app
  template:
    metadata:
      labels:
        app: ecai-app
    spec:
      containers:
      - name: ecai-container
        image: aswin2404/ecai-app:latest  # add tag if needed
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ecai-service
  labels:
    app: ecai-app
spec:
  selector:
    app: ecai-app
  type: NodePort
  ports:
  - nodePort: 31030    
    port: 80
    targetPort: 80
