apiVersion: apps/v1
kind: Deployment
metadata:
  name: ECAI-deploy
  labels:
    app: ECAI-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ECAI-app
  template:
    metadata:
      labels:
        app: ECAI-app
    spec:
      containers:
      - name: banking-finance-container
        image: aswin2404/ECAI-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ECAI-service
  labels:
    app: ECAI-app
spec:
  selector:
    app: ECAI-app

  type: NodePort
  ports:
  - nodePort: 31030    
    port: 80
    targetPort: 80
